// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

interface FooterDocumentData {}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type FormDocumentDataSlicesSlice = TextSlice;

/**
 * Content for Form documents
 */
interface FormDocumentData {
  /**
   * Title field in *Form*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Form*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Submit button text field in *Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.submit_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_button_text: prismic.KeyTextField;

  /**
   * Slice Zone field in *Form*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: form.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FormDocumentDataSlicesSlice>;
}

/**
 * Form document from Prismic
 *
 * - **API ID**: `form`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FormDocumentData>, "form", Lang>;

type HomepageDocumentDataSlicesSlice = MediaAndTextSlice | TextContentSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaTitle
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  metaTitle: prismic.KeyTextField;

  /**
   * Meta description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaDescription
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * Meta image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metaImage
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  metaImage: prismic.ImageField<never>;

  /**
   * Canonical URL field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.canonical_url
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Keywords field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  keywords: prismic.KeyTextField;

  /**
   * Hide this page from search results? field in *Homepage*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.hide_page
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_page: prismic.BooleanField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = MenuItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FormSlice
  | MediaAndTextSlice
  | TextContentSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaTitle
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  metaTitle: prismic.KeyTextField;

  /**
   * Meta description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaDescription
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  metaDescription: prismic.KeyTextField;

  /**
   * Meta image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.metaImage
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  metaImage: prismic.ImageField<never>;

  /**
   * Canonical URL field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.canonical_url
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  canonical_url: prismic.KeyTextField;

  /**
   * Keywords field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  keywords: prismic.KeyTextField;

  /**
   * Hide this page from search results? field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.hide_page
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_page: prismic.BooleanField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Redirects → redirects*
 */
export interface RedirectsDocumentDataRedirectsItem {
  /**
   * Old path field in *Redirects → redirects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[].old
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  old: prismic.KeyTextField;

  /**
   * New path field in *Redirects → redirects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[].new
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  new: prismic.KeyTextField;

  /**
   * Status field in *Redirects → redirects*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 301
   * - **API ID Path**: redirects.redirects[].status
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  status: prismic.SelectField<"301" | "302", "filled">;
}

/**
 * Content for Redirects documents
 */
interface RedirectsDocumentData {
  /**
   * redirects field in *Redirects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  redirects: prismic.GroupField<Simplify<RedirectsDocumentDataRedirectsItem>>;
}

/**
 * Redirects document from Prismic
 *
 * - **API ID**: `redirects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectsDocumentData>,
    "redirects",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Logo White field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo_white
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_white: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | FormDocument
  | HomepageDocument
  | NavigationDocument
  | PageDocument
  | RedirectsDocument
  | SettingsDocument;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Select form field in *Form → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.form
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  form: prismic.ContentRelationshipField<"form">;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *MediaAndText → Default → Primary*
 */
export interface MediaAndTextSliceDefaultPrimary {
  /**
   * Image or Video field in *MediaAndText → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: media_and_text.default.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Content field in *MediaAndText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_and_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Type field in *MediaAndText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose type
   * - **Default Value**: service
   * - **API ID Path**: media_and_text.default.primary.type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"service" | "reference", "filled">;
}

/**
 * Default variation for MediaAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaAndTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaAndTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MediaAndText → Image to the right → Primary*
 */
export interface MediaAndTextSliceImageToTheRightPrimary {
  /**
   * Image or Video field in *MediaAndText → Image to the right → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: media_and_text.imageToTheRight.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Content field in *MediaAndText → Image to the right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_and_text.imageToTheRight.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Type field in *MediaAndText → Image to the right → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose type
   * - **Default Value**: service
   * - **API ID Path**: media_and_text.imageToTheRight.primary.type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"service" | "reference", "filled">;
}

/**
 * Image to the right variation for MediaAndText Slice
 *
 * - **API ID**: `imageToTheRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaAndTextSliceImageToTheRight = prismic.SharedSliceVariation<
  "imageToTheRight",
  Simplify<MediaAndTextSliceImageToTheRightPrimary>,
  never
>;

/**
 * Slice variation for *MediaAndText*
 */
type MediaAndTextSliceVariation =
  | MediaAndTextSliceDefault
  | MediaAndTextSliceImageToTheRight;

/**
 * MediaAndText Shared Slice
 *
 * - **API ID**: `media_and_text`
 * - **Description**: MediaAndText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaAndTextSlice = prismic.SharedSlice<
  "media_and_text",
  MediaAndTextSliceVariation
>;

/**
 * Primary content in *TextContent → Default → Primary*
 */
export interface TextContentSliceDefaultPrimary {
  /**
   * Content field in *TextContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextContent*
 */
type TextContentSliceVariation = TextContentSliceDefault;

/**
 * TextContent Shared Slice
 *
 * - **API ID**: `text_content`
 * - **Description**: TextContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextContentSlice = prismic.SharedSlice<
  "text_content",
  TextContentSliceVariation
>;

/**
 * Primary content in *Field → Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Label field in *Field → Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Required field in *Field → Text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.default.primary.required
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  required: prismic.BooleanField;

  /**
   * Placeholder field in *Field → Text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Size field in *Field → Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: text.default.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"100%" | "50%" | "33%", "filled">;
}

/**
 * Text variation for Field Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Field → Textarea → Primary*
 */
export interface TextSliceTextareaPrimary {
  /**
   * Label field in *Field → Textarea → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textarea.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Required field in *Field → Textarea → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.textarea.primary.required
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  required: prismic.BooleanField;

  /**
   * Placeholder field in *Field → Textarea → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textarea.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Size field in *Field → Textarea → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: text.textarea.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"100%" | "50%" | "33%", "filled">;
}

/**
 * Textarea variation for Field Slice
 *
 * - **API ID**: `textarea`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceTextarea = prismic.SharedSliceVariation<
  "textarea",
  Simplify<TextSliceTextareaPrimary>,
  never
>;

/**
 * Primary content in *Field → Select → Primary*
 */
export interface TextSliceSelectPrimary {
  /**
   * Label field in *Field → Select → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.select.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Required field in *Field → Select → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.select.primary.required
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  required: prismic.BooleanField;

  /**
   * Placeholder field in *Field → Select → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.select.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Size field in *Field → Select → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: text.select.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"100%" | "50%" | "33%", "filled">;
}

/**
 * Primary content in *Field → Items*
 */
export interface TextSliceSelectItem {
  /**
   * value : text field in *Field → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: red : Röd
   * - **API ID Path**: text.items[].option
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  option: prismic.KeyTextField;
}

/**
 * Select variation for Field Slice
 *
 * - **API ID**: `select`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceSelect = prismic.SharedSliceVariation<
  "select",
  Simplify<TextSliceSelectPrimary>,
  Simplify<TextSliceSelectItem>
>;

/**
 * Primary content in *Field → Consent → Primary*
 */
export interface TextSliceConsentPrimary {
  /**
   * Label field in *Field → Consent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.consent.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Required field in *Field → Consent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.consent.primary.required
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  required: prismic.BooleanField;

  /**
   * Consent message field in *Field → Consent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.consent.primary.consent_message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  consent_message: prismic.RichTextField;
}

/**
 * Consent variation for Field Slice
 *
 * - **API ID**: `consent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceConsent = prismic.SharedSliceVariation<
  "consent",
  Simplify<TextSliceConsentPrimary>,
  never
>;

/**
 * Primary content in *Field → Email → Primary*
 */
export interface TextSliceEmailPrimary {
  /**
   * Label field in *Field → Email → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.email.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Required field in *Field → Email → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.email.primary.required
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  required: prismic.BooleanField;

  /**
   * Placeholder field in *Field → Email → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.email.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Size field in *Field → Email → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 100%
   * - **API ID Path**: text.email.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"100%" | "50%" | "33%", "filled">;
}

/**
 * Email variation for Field Slice
 *
 * - **API ID**: `email`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceEmail = prismic.SharedSliceVariation<
  "email",
  Simplify<TextSliceEmailPrimary>,
  never
>;

/**
 * Slice variation for *Field*
 */
type TextSliceVariation =
  | TextSliceDefault
  | TextSliceTextarea
  | TextSliceSelect
  | TextSliceConsent
  | TextSliceEmail;

/**
 * Field Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *MenuItem → Default → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Text field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *MenuItem → Items*
 */
export interface MenuItemSliceDefaultItem {
  /**
   * Text field in *MenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  Simplify<MenuItemSliceDefaultItem>
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FormDocument,
      FormDocumentData,
      FormDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      RedirectsDocument,
      RedirectsDocumentData,
      RedirectsDocumentDataRedirectsItem,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      MediaAndTextSlice,
      MediaAndTextSliceDefaultPrimary,
      MediaAndTextSliceImageToTheRightPrimary,
      MediaAndTextSliceVariation,
      MediaAndTextSliceDefault,
      MediaAndTextSliceImageToTheRight,
      TextContentSlice,
      TextContentSliceDefaultPrimary,
      TextContentSliceVariation,
      TextContentSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceTextareaPrimary,
      TextSliceSelectPrimary,
      TextSliceSelectItem,
      TextSliceConsentPrimary,
      TextSliceEmailPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceTextarea,
      TextSliceSelect,
      TextSliceConsent,
      TextSliceEmail,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceDefaultItem,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
    };
  }
}
