// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  media_and_text: defineAsyncComponent(
    () => import("./MediaAndText/index.vue"),
  ),
  references: defineAsyncComponent(() => import("./ReferenceList/index.vue")),
  text_content: defineAsyncComponent(() => import("./TextContent/index.vue")),
  timeline: defineAsyncComponent(() => import("./Timeline/index.vue")),
});
